-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: Men_Meet, v22 by asdf74591@gmail.com *****



-- ************************************** `mentoss123`.`Alert_Table`

CREATE TABLE `mentoss123`.`Alert_Table`
(
 `Alert_Count`    int NOT NULL AUTO_INCREMENT ,
 `Alert_User_ID`  varchar(20) NOT NULL ,
 `Alert_Contents` varchar(100) NOT NULL ,
 `Alert_Time`     datetime NOT NULL ,
 `Alert_Check`    bit NOT NULL ,

PRIMARY KEY (`Alert_Count`, `Alert_User_ID`),
KEY `FK_197` (`Alert_User_ID`),
CONSTRAINT `FK_195` FOREIGN KEY `FK_197` (`Alert_User_ID`) REFERENCES `mentoss123`.`User_Table` (`User_Char_User_ID`)
);



-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: Men_Meet, v22 by asdf74591@gmail.com *****



-- ************************************** `mentoss123`.`Manager_Table`

CREATE TABLE `mentoss123`.`Manager_Table`
(
 `Manager_ID`    varchar(20) NOT NULL ,
 `Manager_PW`    varchar(20) NOT NULL ,
 `Manager_Name`  varchar(15) NOT NULL ,
 `Manager_Image` varchar(100) NOT NULL ,

PRIMARY KEY (`Manager_ID`)
);


-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: Men_Meet, v22 by asdf74591@gmail.com *****



-- ************************************** `mentoss123`.`Menti_Table`

CREATE TABLE `mentoss123`.`Menti_Table`
(
 `Menti_Number`      int NOT NULL AUTO_INCREMENT ,
 `User_Char_User_ID` varchar(20) NOT NULL ,
 `Menti_Category`    varchar(20) NOT NULL ,
 `Menti_Explanation` varchar(300) NULL ,
 `Menti_Title`       varchar(20) NOT NULL ,

PRIMARY KEY (`Menti_Number`, `User_Char_User_ID`),
KEY `FK_48` (`User_Char_User_ID`),
CONSTRAINT `FK_USER_MENTI` FOREIGN KEY `FK_48` (`User_Char_User_ID`) REFERENCES `mentoss123`.`User_Table` (`User_Char_User_ID`)
);




-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: Men_Meet, v22 by asdf74591@gmail.com *****



-- ************************************** `mentoss123`.`Mento_Table`

CREATE TABLE `mentoss123`.`Mento_Table`
(
 `Mento_Number`      int NOT NULL AUTO_INCREMENT ,
 `Mento__User_ID`    varchar(20) NOT NULL ,
 `Mento_Category`    varchar(20) NOT NULL ,
 `Mento_Explanation` varchar(300) NULL ,
 `Mento_Title`       varchar(20) NOT NULL ,

PRIMARY KEY (`Mento_Number`, `Mento__User_ID`),
KEY `FK_35` (`Mento__User_ID`),
CONSTRAINT `FK_User_Mento` FOREIGN KEY `FK_35` (`Mento__User_ID`) REFERENCES `mentoss123`.`User_Table` (`User_Char_User_ID`)
);





-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: Men_Meet, v22 by asdf74591@gmail.com *****



-- ************************************** `mentoss123`.`QnA_Table`

CREATE TABLE `mentoss123`.`QnA_Table`
(
 `QnA_Post_Number`       bigint NOT NULL AUTO_INCREMENT ,
 `User_Char_User_ID`     varchar(20) NOT NULL ,
 `QnA_Manager_ID`        varchar(20) NULL ,
 `QnA_Question_Title`    varchar(50) NOT NULL ,
 `QnA_Question_Contents` varchar(300) NULL ,
 `QnA_Answer_Contents`   varchar(300) NOT NULL ,
 `QnA_PW`                varchar(10) NOT NULL ,
 `QnA_Is_Secret`         tinyint NOT NULL ,
 `QnA_Category`          tinyint NOT NULL ,

PRIMARY KEY (`QnA_Post_Number`, `User_Char_User_ID`),
KEY `FK_149` (`QnA_Manager_ID`),
CONSTRAINT `FK_Mnager_QnA` FOREIGN KEY `FK_149` (`QnA_Manager_ID`) REFERENCES `mentoss123`.`Manager_Table` (`Manager_ID`),
KEY `FK_65` (`User_Char_User_ID`),
CONSTRAINT `FK_User_QnA` FOREIGN KEY `FK_65` (`User_Char_User_ID`) REFERENCES `mentoss123`.`User_Table` (`User_Char_User_ID`)
);





-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: Men_Meet, v22 by asdf74591@gmail.com *****



-- ************************************** `mentoss123`.`Reservation_Table`

CREATE TABLE `mentoss123`.`Reservation_Table`
(
 `Reservation_PostNumber`        int NOT NULL ,
 `Reservation_ReservationNumber` int NOT NULL AUTO_INCREMENT ,
 `Reservation_Mento_ID`          varchar(20) NOT NULL ,
 `Reservation_Menti_ID`          varchar(20) NOT NULL ,
 `Reservation_StartTime`         datetime NOT NULL ,
 `Reservation_EndTime`           datetime NULL ,
 `Reservation_Place`             varchar(45) NOT NULL ,
 `Reservation_Category`          varchar(20) NOT NULL ,
 `Reservation_IsMento_IsMenti`   bit NOT NULL ,

PRIMARY KEY (`Reservation_PostNumber`, `Reservation_ReservationNumber`, `Reservation_Mento_ID`, `Reservation_Menti_ID`),
KEY `FK_182` (`Reservation_Mento_ID`),
CONSTRAINT `FK_User_Reservation_Mento` FOREIGN KEY `FK_182` (`Reservation_Mento_ID`) REFERENCES `mentoss123`.`User_Table` (`User_Char_User_ID`),
KEY `FK_186` (`Reservation_Menti_ID`),
CONSTRAINT `FK_User_Reservation_Menti` FOREIGN KEY `FK_186` (`Reservation_Menti_ID`) REFERENCES `mentoss123`.`User_Table` (`User_Char_User_ID`)
);





-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: Men_Meet, v22 by asdf74591@gmail.com *****



-- ************************************** `mentoss123`.`Review_Table`

CREATE TABLE `mentoss123`.`Review_Table`
(
 `Reservation_PostNumber`        int NOT NULL ,
 `Reservation_ReservationNumber` int NOT NULL ,
 `Reservation_Mento_ID`          varchar(20) NOT NULL ,
 `Reservation_Menti_ID`          varchar(20) NOT NULL ,
 `Review_Score`                  tinyint unsigned NOT NULL ,
 `Review_Contents`               varchar(100) NULL ,

PRIMARY KEY (`Reservation_PostNumber`, `Reservation_ReservationNumber`, `Reservation_Mento_ID`, `Reservation_Menti_ID`),
KEY `FK_125` (`Reservation_PostNumber`, `Reservation_ReservationNumber`, `Reservation_Mento_ID`, `Reservation_Menti_ID`),
CONSTRAINT `FK_Reservation_Review` FOREIGN KEY `FK_125` (`Reservation_PostNumber`, `Reservation_ReservationNumber`, `Reservation_Mento_ID`, `Reservation_Menti_ID`) REFERENCES `mentoss123`.`Reservation_Table` (`Reservation_PostNumber`, `Reservation_ReservationNumber`, `Reservation_Mento_ID`, `Reservation_Menti_ID`)
);





-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: Men_Meet, v22 by asdf74591@gmail.com *****



-- ************************************** `mentoss123`.`School_Table`

CREATE TABLE `mentoss123`.`School_Table`
(
 `School_Department`           varchar(45) NOT NULL ,
 `School_Department_Introduce` varchar(1000) NOT NULL ,

PRIMARY KEY (`School_Department`)
);





-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: Men_Meet, v22 by asdf74591@gmail.com *****



-- ************************************** `mentoss123`.`User_Char_Table`

CREATE TABLE `mentoss123`.`User_Char_Table`
(
 `User_Char_User_ID`  varchar(20) NOT NULL ,
 `User_Char_Hat`      int NOT NULL ,
 `User_Char_Eyes`     int NOT NULL ,
 `User_Char_Face`     int NOT NULL ,
 `User_Char_Color`    varchar(20) NOT NULL ,
 `User_Char_Size`     int NOT NULL ,
 `User_Char_Place`    varchar(45) NULL ,
 `User_Char_LastUser` varchar(45) NULL ,

PRIMARY KEY (`User_Char_User_ID`),
KEY `FK_130` (`User_Char_User_ID`),
CONSTRAINT `FK_User_User_Char` FOREIGN KEY `FK_130` (`User_Char_User_ID`) REFERENCES `mentoss123`.`User_Table` (`User_Char_User_ID`)
);




-- **************************** SqlDBM: MySQL ***************************
-- ****** Generated by SqlDBM: Men_Meet, v22 by asdf74591@gmail.com *****



-- ************************************** `mentoss123`.`User_Table`

CREATE TABLE `mentoss123`.`User_Table`
(
 `User_Char_User_ID`  varchar(20) NOT NULL ,
 `User_Char_Hat`      int NOT NULL ,
 `User_Char_Eyes`     int NOT NULL ,
 `User_Char_Face`     int NOT NULL ,
 `User_Char_Color`    varchar(20) NOT NULL ,
 `User_Char_Size`     int NOT NULL ,
 `User_Char_Place`    varchar(45) NOT NULL ,
 `User_Char_LastUser` varchar(45) NOT NULL ,

PRIMARY KEY (`User_Char_User_ID`)
);